<?php

return [
	'bind' => [],
	'listen' => [
		'OnVerifierCodeReadAfter' => ['little\verifier\event\OnVerifierCodeReadAfter'],
		'OnVerifierCodeSetIncByField' => ['little\verifier\event\OnVerifierCodeSetIncByField'],
		'OnVerifierCodeSetDecByField' => ['little\verifier\event\OnVerifierCodeSetDecByField'],
		'OnVerifierCodeQueryById' => ['little\verifier\event\OnVerifierCodeQueryById'],
		'OnVerifierCodeQueryByField' => ['little\verifier\event\OnVerifierCodeQueryByField'],
		'OnVerifierCodeQueryByFind' => ['little\verifier\event\OnVerifierCodeQueryByFind'],
		'OnVerifierCodeQueryByList' => ['little\verifier\event\OnVerifierCodeQueryByList'],
		'OnVerifierCodeDeleteById' => ['little\verifier\event\OnVerifierCodeDeleteById'],
		'OnVerifierCodeDeleteByWhere' => ['little\verifier\event\OnVerifierCodeDeleteByWhere'],
		'OnVerifierCodeUpdateById' => ['little\verifier\event\OnVerifierCodeUpdateById'],
		'OnVerifierCodeUpdateByWhere' => ['little\verifier\event\OnVerifierCodeUpdateByWhere'],
		'OnVerifierCodeSave' => ['little\verifier\event\OnVerifierCodeSave'],
		'OnVerifierUserReadAfter' => ['little\verifier\event\OnVerifierUserReadAfter'],
		'OnVerifierUserSetIncByField' => ['little\verifier\event\OnVerifierUserSetIncByField'],
		'OnVerifierUserSetDecByField' => ['little\verifier\event\OnVerifierUserSetDecByField'],
		'OnVerifierUserQueryById' => ['little\verifier\event\OnVerifierUserQueryById'],
		'OnVerifierUserQueryByField' => ['little\verifier\event\OnVerifierUserQueryByField'],
		'OnVerifierUserQueryByFind' => ['little\verifier\event\OnVerifierUserQueryByFind'],
		'OnVerifierUserQueryByList' => ['little\verifier\event\OnVerifierUserQueryByList'],
		'OnVerifierUserDeleteById' => ['little\verifier\event\OnVerifierUserDeleteById'],
		'OnVerifierUserDeleteByWhere' => ['little\verifier\event\OnVerifierUserDeleteByWhere'],
		'OnVerifierUserUpdateById' => ['little\verifier\event\OnVerifierUserUpdateById'],
		'OnVerifierUserUpdateByWhere' => ['little\verifier\event\OnVerifierUserUpdateByWhere'],
		'OnVerifierUserSave' => ['little\verifier\event\OnVerifierUserSave'],
	],
	'subscribe' => [],
];