<?php

return [
	'bind' => [],
	'listen' => [
		'OnUserReadAfter' => ['little\user\event\OnUserReadAfter'],
		'OnUserSetIncByField' => ['little\user\event\OnUserSetIncByField'],
		'OnUserSetDecByField' => ['little\user\event\OnUserSetDecByField'],
		'OnUserQueryById' => ['little\user\event\OnUserQueryById'],
		'OnUserQueryByField' => ['little\user\event\OnUserQueryByField'],
		'OnUserQueryByFind' => ['little\user\event\OnUserQueryByFind'],
		'OnUserQueryByList' => ['little\user\event\OnUserQueryByList'],
		'OnUserDeleteById' => ['little\user\event\OnUserDeleteById'],
		'OnUserDeleteByWhere' => ['little\user\event\OnUserDeleteByWhere'],
		'OnUserUpdateById' => ['little\user\event\OnUserUpdateById'],
		'OnUserUpdateByWhere' => ['little\user\event\OnUserUpdateByWhere'],
		'OnUserSave' => ['little\user\event\OnUserSave'],
		'OnUserLogReadAfter' => ['little\user\event\OnUserLogReadAfter'],
		'OnUserLogSetIncByField' => ['little\user\event\OnUserLogSetIncByField'],
		'OnUserLogSetDecByField' => ['little\user\event\OnUserLogSetDecByField'],
		'OnUserLogQueryById' => ['little\user\event\OnUserLogQueryById'],
		'OnUserLogQueryByField' => ['little\user\event\OnUserLogQueryByField'],
		'OnUserLogQueryByFind' => ['little\user\event\OnUserLogQueryByFind'],
		'OnUserLogQueryByList' => ['little\user\event\OnUserLogQueryByList'],
		'OnUserLogDeleteById' => ['little\user\event\OnUserLogDeleteById'],
		'OnUserLogDeleteByWhere' => ['little\user\event\OnUserLogDeleteByWhere'],
		'OnUserLogUpdateById' => ['little\user\event\OnUserLogUpdateById'],
		'OnUserLogUpdateByWhere' => ['little\user\event\OnUserLogUpdateByWhere'],
		'OnUserLogSave' => ['little\user\event\OnUserLogSave'],
	],
	'subscribe' => [],
];