<?php

return [
	'service.goods.AttrClassService' => 'little\goods\service\api\AttrClassService',
	'service.goods.AttrClassBrandService' => 'little\goods\service\api\AttrClassBrandService',
	'service.goods.AttrHasService' => 'little\goods\service\api\AttrHasService',
	'service.goods.AttributeService' => 'little\goods\service\api\AttributeService',
	'service.goods.AttributeValueService' => 'little\goods\service\api\AttributeValueService',
	'service.goods.BrandService' => 'little\goods\service\api\BrandService',
	'service.goods.BrowseService' => 'little\goods\service\api\BrowseService',
	'service.goods.CartService' => 'little\goods\service\api\CartService',
	'service.goods.CategoryService' => 'little\goods\service\api\CategoryService',
	'service.goods.CollectService' => 'little\goods\service\api\CollectService',
	'service.goods.EvaluateService' => 'little\goods\service\api\EvaluateService',
	'service.goods.ExportService' => 'little\goods\service\api\ExportService',
	'service.goods.GoodsService' => 'little\goods\service\api\GoodsService',
	'service.goods.ShopCategoryService' => 'little\goods\service\api\ShopCategoryService',
	'service.goods.SkuService' => 'little\goods\service\api\SkuService',
	'service.goods.VirtualService' => 'little\goods\service\api\VirtualService',
	'service.admin.goods.AttrClassService' => 'little\goods\service\admin\AttrClassService',
	'service.admin.goods.AttrClassBrandService' => 'little\goods\service\admin\AttrClassBrandService',
	'service.admin.goods.AttrHasService' => 'little\goods\service\admin\AttrHasService',
	'service.admin.goods.AttributeService' => 'little\goods\service\admin\AttributeService',
	'service.admin.goods.AttributeValueService' => 'little\goods\service\admin\AttributeValueService',
	'service.admin.goods.BrandService' => 'little\goods\service\admin\BrandService',
	'service.admin.goods.BrowseService' => 'little\goods\service\admin\BrowseService',
	'service.admin.goods.CartService' => 'little\goods\service\admin\CartService',
	'service.admin.goods.CategoryService' => 'little\goods\service\admin\CategoryService',
	'service.admin.goods.CollectService' => 'little\goods\service\admin\CollectService',
	'service.admin.goods.EvaluateService' => 'little\goods\service\admin\EvaluateService',
	'service.admin.goods.ExportService' => 'little\goods\service\admin\ExportService',
	'service.admin.goods.GoodsService' => 'little\goods\service\admin\GoodsService',
	'service.admin.goods.ShopCategoryService' => 'little\goods\service\admin\ShopCategoryService',
	'service.admin.goods.SkuService' => 'little\goods\service\admin\SkuService',
	'service.admin.goods.VirtualService' => 'little\goods\service\admin\VirtualService',
];