<?php

return [
	'service.member.AccountService' => 'little\member\service\api\AccountService',
	'service.member.AddressService' => 'little\member\service\api\AddressService',
	'service.member.AuthService' => 'little\member\service\api\AuthService',
	'service.member.BankService' => 'little\member\service\api\BankService',
	'service.member.LabelService' => 'little\member\service\api\LabelService',
	'service.member.LevelService' => 'little\member\service\api\LevelService',
	'service.member.LogService' => 'little\member\service\api\LogService',
	'service.member.RechargeService' => 'little\member\service\api\RechargeService',
	'service.member.RechargeCardService' => 'little\member\service\api\RechargeCardService',
	'service.member.RechargeOrderService' => 'little\member\service\api\RechargeOrderService',
	'service.member.UserService' => 'little\member\service\api\UserService',
	'service.member.WithdrawService' => 'little\member\service\api\WithdrawService',
	'service.admin.member.AccountService' => 'little\member\service\admin\AccountService',
	'service.admin.member.AddressService' => 'little\member\service\admin\AddressService',
	'service.admin.member.AuthService' => 'little\member\service\admin\AuthService',
	'service.admin.member.BankService' => 'little\member\service\admin\BankService',
	'service.admin.member.LabelService' => 'little\member\service\admin\LabelService',
	'service.admin.member.LevelService' => 'little\member\service\admin\LevelService',
	'service.admin.member.LogService' => 'little\member\service\admin\LogService',
	'service.admin.member.RechargeService' => 'little\member\service\admin\RechargeService',
	'service.admin.member.RechargeCardService' => 'little\member\service\admin\RechargeCardService',
	'service.admin.member.RechargeOrderService' => 'little\member\service\admin\RechargeOrderService',
	'service.admin.member.UserService' => 'little\member\service\admin\UserService',
	'service.admin.member.WithdrawService' => 'little\member\service\admin\WithdrawService',
];