<?php

return [
	'bind' => [],
	'listen' => [
		'OnPrinterPrinterReadAfter' => ['little\printer\event\OnPrinterPrinterReadAfter'],
		'OnPrinterPrinterSetIncByField' => ['little\printer\event\OnPrinterPrinterSetIncByField'],
		'OnPrinterPrinterSetDecByField' => ['little\printer\event\OnPrinterPrinterSetDecByField'],
		'OnPrinterPrinterQueryById' => ['little\printer\event\OnPrinterPrinterQueryById'],
		'OnPrinterPrinterQueryByField' => ['little\printer\event\OnPrinterPrinterQueryByField'],
		'OnPrinterPrinterQueryByFind' => ['little\printer\event\OnPrinterPrinterQueryByFind'],
		'OnPrinterPrinterQueryByList' => ['little\printer\event\OnPrinterPrinterQueryByList'],
		'OnPrinterPrinterDeleteById' => ['little\printer\event\OnPrinterPrinterDeleteById'],
		'OnPrinterPrinterDeleteByWhere' => ['little\printer\event\OnPrinterPrinterDeleteByWhere'],
		'OnPrinterPrinterUpdateById' => ['little\printer\event\OnPrinterPrinterUpdateById'],
		'OnPrinterPrinterUpdateByWhere' => ['little\printer\event\OnPrinterPrinterUpdateByWhere'],
		'OnPrinterPrinterSave' => ['little\printer\event\OnPrinterPrinterSave'],
		'OnPrinterTemplateReadAfter' => ['little\printer\event\OnPrinterTemplateReadAfter'],
		'OnPrinterTemplateSetIncByField' => ['little\printer\event\OnPrinterTemplateSetIncByField'],
		'OnPrinterTemplateSetDecByField' => ['little\printer\event\OnPrinterTemplateSetDecByField'],
		'OnPrinterTemplateQueryById' => ['little\printer\event\OnPrinterTemplateQueryById'],
		'OnPrinterTemplateQueryByField' => ['little\printer\event\OnPrinterTemplateQueryByField'],
		'OnPrinterTemplateQueryByFind' => ['little\printer\event\OnPrinterTemplateQueryByFind'],
		'OnPrinterTemplateQueryByList' => ['little\printer\event\OnPrinterTemplateQueryByList'],
		'OnPrinterTemplateDeleteById' => ['little\printer\event\OnPrinterTemplateDeleteById'],
		'OnPrinterTemplateDeleteByWhere' => ['little\printer\event\OnPrinterTemplateDeleteByWhere'],
		'OnPrinterTemplateUpdateById' => ['little\printer\event\OnPrinterTemplateUpdateById'],
		'OnPrinterTemplateUpdateByWhere' => ['little\printer\event\OnPrinterTemplateUpdateByWhere'],
		'OnPrinterTemplateSave' => ['little\printer\event\OnPrinterTemplateSave'],
	],
	'subscribe' => [],
];