<?php

return [
	'bind' => [],
	'listen' => [
		'OnPrinterReadAfter' => ['little\printer\event\OnPrinterReadAfter'],
		'OnPrinterSetIncByField' => ['little\printer\event\OnPrinterSetIncByField'],
		'OnPrinterSetDecByField' => ['little\printer\event\OnPrinterSetDecByField'],
		'OnPrinterQueryById' => ['little\printer\event\OnPrinterQueryById'],
		'OnPrinterQueryByField' => ['little\printer\event\OnPrinterQueryByField'],
		'OnPrinterQueryByFind' => ['little\printer\event\OnPrinterQueryByFind'],
		'OnPrinterQueryByList' => ['little\printer\event\OnPrinterQueryByList'],
		'OnPrinterDeleteById' => ['little\printer\event\OnPrinterDeleteById'],
		'OnPrinterDeleteByWhere' => ['little\printer\event\OnPrinterDeleteByWhere'],
		'OnPrinterUpdateById' => ['little\printer\event\OnPrinterUpdateById'],
		'OnPrinterUpdateByWhere' => ['little\printer\event\OnPrinterUpdateByWhere'],
		'OnPrinterSave' => ['little\printer\event\OnPrinterSave'],
		'OnPrinterTemplateReadAfter' => ['little\printer\event\OnPrinterTemplateReadAfter'],
		'OnPrinterTemplateSetIncByField' => ['little\printer\event\OnPrinterTemplateSetIncByField'],
		'OnPrinterTemplateSetDecByField' => ['little\printer\event\OnPrinterTemplateSetDecByField'],
		'OnPrinterTemplateQueryById' => ['little\printer\event\OnPrinterTemplateQueryById'],
		'OnPrinterTemplateQueryByField' => ['little\printer\event\OnPrinterTemplateQueryByField'],
		'OnPrinterTemplateQueryByFind' => ['little\printer\event\OnPrinterTemplateQueryByFind'],
		'OnPrinterTemplateQueryByList' => ['little\printer\event\OnPrinterTemplateQueryByList'],
		'OnPrinterTemplateDeleteById' => ['little\printer\event\OnPrinterTemplateDeleteById'],
		'OnPrinterTemplateDeleteByWhere' => ['little\printer\event\OnPrinterTemplateDeleteByWhere'],
		'OnPrinterTemplateUpdateById' => ['little\printer\event\OnPrinterTemplateUpdateById'],
		'OnPrinterTemplateUpdateByWhere' => ['little\printer\event\OnPrinterTemplateUpdateByWhere'],
		'OnPrinterTemplateSave' => ['little\printer\event\OnPrinterTemplateSave'],
	],
	'subscribe' => [],
];