<?php

return [
	'bind' => [],
	'listen' => [
		'OnSeckillGoodsReadAfter' => ['little\seckill\event\OnSeckillGoodsReadAfter'],
		'OnSeckillGoodsSetIncByField' => ['little\seckill\event\OnSeckillGoodsSetIncByField'],
		'OnSeckillGoodsSetDecByField' => ['little\seckill\event\OnSeckillGoodsSetDecByField'],
		'OnSeckillGoodsQueryById' => ['little\seckill\event\OnSeckillGoodsQueryById'],
		'OnSeckillGoodsQueryByField' => ['little\seckill\event\OnSeckillGoodsQueryByField'],
		'OnSeckillGoodsQueryByFind' => ['little\seckill\event\OnSeckillGoodsQueryByFind'],
		'OnSeckillGoodsQueryByList' => ['little\seckill\event\OnSeckillGoodsQueryByList'],
		'OnSeckillGoodsDeleteById' => ['little\seckill\event\OnSeckillGoodsDeleteById'],
		'OnSeckillGoodsDeleteByWhere' => ['little\seckill\event\OnSeckillGoodsDeleteByWhere'],
		'OnSeckillGoodsUpdateById' => ['little\seckill\event\OnSeckillGoodsUpdateById'],
		'OnSeckillGoodsUpdateByWhere' => ['little\seckill\event\OnSeckillGoodsUpdateByWhere'],
		'OnSeckillGoodsSave' => ['little\seckill\event\OnSeckillGoodsSave'],
		'OnSeckillSeckillReadAfter' => ['little\seckill\event\OnSeckillSeckillReadAfter'],
		'OnSeckillSeckillSetIncByField' => ['little\seckill\event\OnSeckillSeckillSetIncByField'],
		'OnSeckillSeckillSetDecByField' => ['little\seckill\event\OnSeckillSeckillSetDecByField'],
		'OnSeckillSeckillQueryById' => ['little\seckill\event\OnSeckillSeckillQueryById'],
		'OnSeckillSeckillQueryByField' => ['little\seckill\event\OnSeckillSeckillQueryByField'],
		'OnSeckillSeckillQueryByFind' => ['little\seckill\event\OnSeckillSeckillQueryByFind'],
		'OnSeckillSeckillQueryByList' => ['little\seckill\event\OnSeckillSeckillQueryByList'],
		'OnSeckillSeckillDeleteById' => ['little\seckill\event\OnSeckillSeckillDeleteById'],
		'OnSeckillSeckillDeleteByWhere' => ['little\seckill\event\OnSeckillSeckillDeleteByWhere'],
		'OnSeckillSeckillUpdateById' => ['little\seckill\event\OnSeckillSeckillUpdateById'],
		'OnSeckillSeckillUpdateByWhere' => ['little\seckill\event\OnSeckillSeckillUpdateByWhere'],
		'OnSeckillSeckillSave' => ['little\seckill\event\OnSeckillSeckillSave'],
	],
	'subscribe' => [],
];