<?php

return [
	'bind' => [],
	'listen' => [
		'OnPaymentPayReadAfter' => ['little\payment\event\OnPaymentPayReadAfter'],
		'OnPaymentPaySetIncByField' => ['little\payment\event\OnPaymentPaySetIncByField'],
		'OnPaymentPaySetDecByField' => ['little\payment\event\OnPaymentPaySetDecByField'],
		'OnPaymentPayQueryById' => ['little\payment\event\OnPaymentPayQueryById'],
		'OnPaymentPayQueryByField' => ['little\payment\event\OnPaymentPayQueryByField'],
		'OnPaymentPayQueryByFind' => ['little\payment\event\OnPaymentPayQueryByFind'],
		'OnPaymentPayQueryByList' => ['little\payment\event\OnPaymentPayQueryByList'],
		'OnPaymentPayDeleteById' => ['little\payment\event\OnPaymentPayDeleteById'],
		'OnPaymentPayDeleteByWhere' => ['little\payment\event\OnPaymentPayDeleteByWhere'],
		'OnPaymentPayUpdateById' => ['little\payment\event\OnPaymentPayUpdateById'],
		'OnPaymentPayUpdateByWhere' => ['little\payment\event\OnPaymentPayUpdateByWhere'],
		'OnPaymentPaySave' => ['little\payment\event\OnPaymentPaySave'],
		'OnPaymentRefundReadAfter' => ['little\payment\event\OnPaymentRefundReadAfter'],
		'OnPaymentRefundSetIncByField' => ['little\payment\event\OnPaymentRefundSetIncByField'],
		'OnPaymentRefundSetDecByField' => ['little\payment\event\OnPaymentRefundSetDecByField'],
		'OnPaymentRefundQueryById' => ['little\payment\event\OnPaymentRefundQueryById'],
		'OnPaymentRefundQueryByField' => ['little\payment\event\OnPaymentRefundQueryByField'],
		'OnPaymentRefundQueryByFind' => ['little\payment\event\OnPaymentRefundQueryByFind'],
		'OnPaymentRefundQueryByList' => ['little\payment\event\OnPaymentRefundQueryByList'],
		'OnPaymentRefundDeleteById' => ['little\payment\event\OnPaymentRefundDeleteById'],
		'OnPaymentRefundDeleteByWhere' => ['little\payment\event\OnPaymentRefundDeleteByWhere'],
		'OnPaymentRefundUpdateById' => ['little\payment\event\OnPaymentRefundUpdateById'],
		'OnPaymentRefundUpdateByWhere' => ['little\payment\event\OnPaymentRefundUpdateByWhere'],
		'OnPaymentRefundSave' => ['little\payment\event\OnPaymentRefundSave'],
	],
	'subscribe' => [],
];