<?php

return [
	'bind' => [],
	'listen' => [
		'OnPaymentReadAfter' => ['little\payment\event\OnPaymentReadAfter'],
		'OnPaymentSetIncByField' => ['little\payment\event\OnPaymentSetIncByField'],
		'OnPaymentSetDecByField' => ['little\payment\event\OnPaymentSetDecByField'],
		'OnPaymentQueryById' => ['little\payment\event\OnPaymentQueryById'],
		'OnPaymentQueryByField' => ['little\payment\event\OnPaymentQueryByField'],
		'OnPaymentQueryByFind' => ['little\payment\event\OnPaymentQueryByFind'],
		'OnPaymentQueryByList' => ['little\payment\event\OnPaymentQueryByList'],
		'OnPaymentDeleteById' => ['little\payment\event\OnPaymentDeleteById'],
		'OnPaymentDeleteByWhere' => ['little\payment\event\OnPaymentDeleteByWhere'],
		'OnPaymentUpdateById' => ['little\payment\event\OnPaymentUpdateById'],
		'OnPaymentUpdateByWhere' => ['little\payment\event\OnPaymentUpdateByWhere'],
		'OnPaymentSave' => ['little\payment\event\OnPaymentSave'],
		'OnPaymentRefundReadAfter' => ['little\payment\event\OnPaymentRefundReadAfter'],
		'OnPaymentRefundSetIncByField' => ['little\payment\event\OnPaymentRefundSetIncByField'],
		'OnPaymentRefundSetDecByField' => ['little\payment\event\OnPaymentRefundSetDecByField'],
		'OnPaymentRefundQueryById' => ['little\payment\event\OnPaymentRefundQueryById'],
		'OnPaymentRefundQueryByField' => ['little\payment\event\OnPaymentRefundQueryByField'],
		'OnPaymentRefundQueryByFind' => ['little\payment\event\OnPaymentRefundQueryByFind'],
		'OnPaymentRefundQueryByList' => ['little\payment\event\OnPaymentRefundQueryByList'],
		'OnPaymentRefundDeleteById' => ['little\payment\event\OnPaymentRefundDeleteById'],
		'OnPaymentRefundDeleteByWhere' => ['little\payment\event\OnPaymentRefundDeleteByWhere'],
		'OnPaymentRefundUpdateById' => ['little\payment\event\OnPaymentRefundUpdateById'],
		'OnPaymentRefundUpdateByWhere' => ['little\payment\event\OnPaymentRefundUpdateByWhere'],
		'OnPaymentRefundSave' => ['little\payment\event\OnPaymentRefundSave'],
	],
	'subscribe' => [],
];