<?php

return [
	'bind' => [],
	'listen' => [
		'OnHelpClassReadAfter' => ['little\help\event\OnHelpClassReadAfter'],
		'OnHelpClassSetIncByField' => ['little\help\event\OnHelpClassSetIncByField'],
		'OnHelpClassSetDecByField' => ['little\help\event\OnHelpClassSetDecByField'],
		'OnHelpClassQueryById' => ['little\help\event\OnHelpClassQueryById'],
		'OnHelpClassQueryByField' => ['little\help\event\OnHelpClassQueryByField'],
		'OnHelpClassQueryByFind' => ['little\help\event\OnHelpClassQueryByFind'],
		'OnHelpClassQueryByList' => ['little\help\event\OnHelpClassQueryByList'],
		'OnHelpClassDeleteById' => ['little\help\event\OnHelpClassDeleteById'],
		'OnHelpClassDeleteByWhere' => ['little\help\event\OnHelpClassDeleteByWhere'],
		'OnHelpClassUpdateById' => ['little\help\event\OnHelpClassUpdateById'],
		'OnHelpClassUpdateByWhere' => ['little\help\event\OnHelpClassUpdateByWhere'],
		'OnHelpClassSave' => ['little\help\event\OnHelpClassSave'],
		'OnHelpListReadAfter' => ['little\help\event\OnHelpListReadAfter'],
		'OnHelpListSetIncByField' => ['little\help\event\OnHelpListSetIncByField'],
		'OnHelpListSetDecByField' => ['little\help\event\OnHelpListSetDecByField'],
		'OnHelpListQueryById' => ['little\help\event\OnHelpListQueryById'],
		'OnHelpListQueryByField' => ['little\help\event\OnHelpListQueryByField'],
		'OnHelpListQueryByFind' => ['little\help\event\OnHelpListQueryByFind'],
		'OnHelpListQueryByList' => ['little\help\event\OnHelpListQueryByList'],
		'OnHelpListDeleteById' => ['little\help\event\OnHelpListDeleteById'],
		'OnHelpListDeleteByWhere' => ['little\help\event\OnHelpListDeleteByWhere'],
		'OnHelpListUpdateById' => ['little\help\event\OnHelpListUpdateById'],
		'OnHelpListUpdateByWhere' => ['little\help\event\OnHelpListUpdateByWhere'],
		'OnHelpListSave' => ['little\help\event\OnHelpListSave'],
	],
	'subscribe' => [],
];