<?php

return [
	'bind' => [],
	'listen' => [
		'OnPintuanGoodsReadAfter' => ['little\pintuan\event\OnPintuanGoodsReadAfter'],
		'OnPintuanGoodsSetIncByField' => ['little\pintuan\event\OnPintuanGoodsSetIncByField'],
		'OnPintuanGoodsSetDecByField' => ['little\pintuan\event\OnPintuanGoodsSetDecByField'],
		'OnPintuanGoodsQueryById' => ['little\pintuan\event\OnPintuanGoodsQueryById'],
		'OnPintuanGoodsQueryByField' => ['little\pintuan\event\OnPintuanGoodsQueryByField'],
		'OnPintuanGoodsQueryByFind' => ['little\pintuan\event\OnPintuanGoodsQueryByFind'],
		'OnPintuanGoodsQueryByList' => ['little\pintuan\event\OnPintuanGoodsQueryByList'],
		'OnPintuanGoodsDeleteById' => ['little\pintuan\event\OnPintuanGoodsDeleteById'],
		'OnPintuanGoodsDeleteByWhere' => ['little\pintuan\event\OnPintuanGoodsDeleteByWhere'],
		'OnPintuanGoodsUpdateById' => ['little\pintuan\event\OnPintuanGoodsUpdateById'],
		'OnPintuanGoodsUpdateByWhere' => ['little\pintuan\event\OnPintuanGoodsUpdateByWhere'],
		'OnPintuanGoodsSave' => ['little\pintuan\event\OnPintuanGoodsSave'],
		'OnPintuanGroupReadAfter' => ['little\pintuan\event\OnPintuanGroupReadAfter'],
		'OnPintuanGroupSetIncByField' => ['little\pintuan\event\OnPintuanGroupSetIncByField'],
		'OnPintuanGroupSetDecByField' => ['little\pintuan\event\OnPintuanGroupSetDecByField'],
		'OnPintuanGroupQueryById' => ['little\pintuan\event\OnPintuanGroupQueryById'],
		'OnPintuanGroupQueryByField' => ['little\pintuan\event\OnPintuanGroupQueryByField'],
		'OnPintuanGroupQueryByFind' => ['little\pintuan\event\OnPintuanGroupQueryByFind'],
		'OnPintuanGroupQueryByList' => ['little\pintuan\event\OnPintuanGroupQueryByList'],
		'OnPintuanGroupDeleteById' => ['little\pintuan\event\OnPintuanGroupDeleteById'],
		'OnPintuanGroupDeleteByWhere' => ['little\pintuan\event\OnPintuanGroupDeleteByWhere'],
		'OnPintuanGroupUpdateById' => ['little\pintuan\event\OnPintuanGroupUpdateById'],
		'OnPintuanGroupUpdateByWhere' => ['little\pintuan\event\OnPintuanGroupUpdateByWhere'],
		'OnPintuanGroupSave' => ['little\pintuan\event\OnPintuanGroupSave'],
		'OnPintuanOrderReadAfter' => ['little\pintuan\event\OnPintuanOrderReadAfter'],
		'OnPintuanOrderSetIncByField' => ['little\pintuan\event\OnPintuanOrderSetIncByField'],
		'OnPintuanOrderSetDecByField' => ['little\pintuan\event\OnPintuanOrderSetDecByField'],
		'OnPintuanOrderQueryById' => ['little\pintuan\event\OnPintuanOrderQueryById'],
		'OnPintuanOrderQueryByField' => ['little\pintuan\event\OnPintuanOrderQueryByField'],
		'OnPintuanOrderQueryByFind' => ['little\pintuan\event\OnPintuanOrderQueryByFind'],
		'OnPintuanOrderQueryByList' => ['little\pintuan\event\OnPintuanOrderQueryByList'],
		'OnPintuanOrderDeleteById' => ['little\pintuan\event\OnPintuanOrderDeleteById'],
		'OnPintuanOrderDeleteByWhere' => ['little\pintuan\event\OnPintuanOrderDeleteByWhere'],
		'OnPintuanOrderUpdateById' => ['little\pintuan\event\OnPintuanOrderUpdateById'],
		'OnPintuanOrderUpdateByWhere' => ['little\pintuan\event\OnPintuanOrderUpdateByWhere'],
		'OnPintuanOrderSave' => ['little\pintuan\event\OnPintuanOrderSave'],
		'OnPintuanPintuanReadAfter' => ['little\pintuan\event\OnPintuanPintuanReadAfter'],
		'OnPintuanPintuanSetIncByField' => ['little\pintuan\event\OnPintuanPintuanSetIncByField'],
		'OnPintuanPintuanSetDecByField' => ['little\pintuan\event\OnPintuanPintuanSetDecByField'],
		'OnPintuanPintuanQueryById' => ['little\pintuan\event\OnPintuanPintuanQueryById'],
		'OnPintuanPintuanQueryByField' => ['little\pintuan\event\OnPintuanPintuanQueryByField'],
		'OnPintuanPintuanQueryByFind' => ['little\pintuan\event\OnPintuanPintuanQueryByFind'],
		'OnPintuanPintuanQueryByList' => ['little\pintuan\event\OnPintuanPintuanQueryByList'],
		'OnPintuanPintuanDeleteById' => ['little\pintuan\event\OnPintuanPintuanDeleteById'],
		'OnPintuanPintuanDeleteByWhere' => ['little\pintuan\event\OnPintuanPintuanDeleteByWhere'],
		'OnPintuanPintuanUpdateById' => ['little\pintuan\event\OnPintuanPintuanUpdateById'],
		'OnPintuanPintuanUpdateByWhere' => ['little\pintuan\event\OnPintuanPintuanUpdateByWhere'],
		'OnPintuanPintuanSave' => ['little\pintuan\event\OnPintuanPintuanSave'],
	],
	'subscribe' => [],
];