<?php

return [
	'bind' => [],
	'listen' => [
		'OnCouponReadAfter' => ['little\coupon\event\OnCouponReadAfter'],
		'OnCouponSetIncByField' => ['little\coupon\event\OnCouponSetIncByField'],
		'OnCouponSetDecByField' => ['little\coupon\event\OnCouponSetDecByField'],
		'OnCouponQueryById' => ['little\coupon\event\OnCouponQueryById'],
		'OnCouponQueryByField' => ['little\coupon\event\OnCouponQueryByField'],
		'OnCouponQueryByFind' => ['little\coupon\event\OnCouponQueryByFind'],
		'OnCouponQueryByList' => ['little\coupon\event\OnCouponQueryByList'],
		'OnCouponDeleteById' => ['little\coupon\event\OnCouponDeleteById'],
		'OnCouponDeleteByWhere' => ['little\coupon\event\OnCouponDeleteByWhere'],
		'OnCouponUpdateById' => ['little\coupon\event\OnCouponUpdateById'],
		'OnCouponUpdateByWhere' => ['little\coupon\event\OnCouponUpdateByWhere'],
		'OnCouponSave' => ['little\coupon\event\OnCouponSave'],
		'OnCouponTypeReadAfter' => ['little\coupon\event\OnCouponTypeReadAfter'],
		'OnCouponTypeSetIncByField' => ['little\coupon\event\OnCouponTypeSetIncByField'],
		'OnCouponTypeSetDecByField' => ['little\coupon\event\OnCouponTypeSetDecByField'],
		'OnCouponTypeQueryById' => ['little\coupon\event\OnCouponTypeQueryById'],
		'OnCouponTypeQueryByField' => ['little\coupon\event\OnCouponTypeQueryByField'],
		'OnCouponTypeQueryByFind' => ['little\coupon\event\OnCouponTypeQueryByFind'],
		'OnCouponTypeQueryByList' => ['little\coupon\event\OnCouponTypeQueryByList'],
		'OnCouponTypeDeleteById' => ['little\coupon\event\OnCouponTypeDeleteById'],
		'OnCouponTypeDeleteByWhere' => ['little\coupon\event\OnCouponTypeDeleteByWhere'],
		'OnCouponTypeUpdateById' => ['little\coupon\event\OnCouponTypeUpdateById'],
		'OnCouponTypeUpdateByWhere' => ['little\coupon\event\OnCouponTypeUpdateByWhere'],
		'OnCouponTypeSave' => ['little\coupon\event\OnCouponTypeSave'],
	],
	'subscribe' => [],
];