<?php

return [
	'bind' => [],
	'listen' => [
		'OnCouponListReadAfter' => ['little\coupon\event\OnCouponListReadAfter'],
		'OnCouponListSetIncByField' => ['little\coupon\event\OnCouponListSetIncByField'],
		'OnCouponListSetDecByField' => ['little\coupon\event\OnCouponListSetDecByField'],
		'OnCouponListQueryById' => ['little\coupon\event\OnCouponListQueryById'],
		'OnCouponListQueryByField' => ['little\coupon\event\OnCouponListQueryByField'],
		'OnCouponListQueryByFind' => ['little\coupon\event\OnCouponListQueryByFind'],
		'OnCouponListQueryByList' => ['little\coupon\event\OnCouponListQueryByList'],
		'OnCouponListDeleteById' => ['little\coupon\event\OnCouponListDeleteById'],
		'OnCouponListDeleteByWhere' => ['little\coupon\event\OnCouponListDeleteByWhere'],
		'OnCouponListUpdateById' => ['little\coupon\event\OnCouponListUpdateById'],
		'OnCouponListUpdateByWhere' => ['little\coupon\event\OnCouponListUpdateByWhere'],
		'OnCouponListSave' => ['little\coupon\event\OnCouponListSave'],
		'OnCouponTypeReadAfter' => ['little\coupon\event\OnCouponTypeReadAfter'],
		'OnCouponTypeSetIncByField' => ['little\coupon\event\OnCouponTypeSetIncByField'],
		'OnCouponTypeSetDecByField' => ['little\coupon\event\OnCouponTypeSetDecByField'],
		'OnCouponTypeQueryById' => ['little\coupon\event\OnCouponTypeQueryById'],
		'OnCouponTypeQueryByField' => ['little\coupon\event\OnCouponTypeQueryByField'],
		'OnCouponTypeQueryByFind' => ['little\coupon\event\OnCouponTypeQueryByFind'],
		'OnCouponTypeQueryByList' => ['little\coupon\event\OnCouponTypeQueryByList'],
		'OnCouponTypeDeleteById' => ['little\coupon\event\OnCouponTypeDeleteById'],
		'OnCouponTypeDeleteByWhere' => ['little\coupon\event\OnCouponTypeDeleteByWhere'],
		'OnCouponTypeUpdateById' => ['little\coupon\event\OnCouponTypeUpdateById'],
		'OnCouponTypeUpdateByWhere' => ['little\coupon\event\OnCouponTypeUpdateByWhere'],
		'OnCouponTypeSave' => ['little\coupon\event\OnCouponTypeSave'],
	],
	'subscribe' => [],
];