<?php

return [
	'bind' => [],
	'listen' => [
		'OnCronReadAfter' => ['little\cron\event\OnCronReadAfter'],
		'OnCronSetIncByField' => ['little\cron\event\OnCronSetIncByField'],
		'OnCronSetDecByField' => ['little\cron\event\OnCronSetDecByField'],
		'OnCronQueryById' => ['little\cron\event\OnCronQueryById'],
		'OnCronQueryByField' => ['little\cron\event\OnCronQueryByField'],
		'OnCronQueryByFind' => ['little\cron\event\OnCronQueryByFind'],
		'OnCronQueryByList' => ['little\cron\event\OnCronQueryByList'],
		'OnCronDeleteById' => ['little\cron\event\OnCronDeleteById'],
		'OnCronDeleteByWhere' => ['little\cron\event\OnCronDeleteByWhere'],
		'OnCronUpdateById' => ['little\cron\event\OnCronUpdateById'],
		'OnCronUpdateByWhere' => ['little\cron\event\OnCronUpdateByWhere'],
		'OnCronSave' => ['little\cron\event\OnCronSave'],
		'OnCronLogReadAfter' => ['little\cron\event\OnCronLogReadAfter'],
		'OnCronLogSetIncByField' => ['little\cron\event\OnCronLogSetIncByField'],
		'OnCronLogSetDecByField' => ['little\cron\event\OnCronLogSetDecByField'],
		'OnCronLogQueryById' => ['little\cron\event\OnCronLogQueryById'],
		'OnCronLogQueryByField' => ['little\cron\event\OnCronLogQueryByField'],
		'OnCronLogQueryByFind' => ['little\cron\event\OnCronLogQueryByFind'],
		'OnCronLogQueryByList' => ['little\cron\event\OnCronLogQueryByList'],
		'OnCronLogDeleteById' => ['little\cron\event\OnCronLogDeleteById'],
		'OnCronLogDeleteByWhere' => ['little\cron\event\OnCronLogDeleteByWhere'],
		'OnCronLogUpdateById' => ['little\cron\event\OnCronLogUpdateById'],
		'OnCronLogUpdateByWhere' => ['little\cron\event\OnCronLogUpdateByWhere'],
		'OnCronLogSave' => ['little\cron\event\OnCronLogSave'],
	],
	'subscribe' => [],
];