<?php

return [
	'bind' => [],
	'listen' => [
		'OnCronCronReadAfter' => ['little\cron\event\OnCronCronReadAfter'],
		'OnCronCronSetIncByField' => ['little\cron\event\OnCronCronSetIncByField'],
		'OnCronCronSetDecByField' => ['little\cron\event\OnCronCronSetDecByField'],
		'OnCronCronQueryById' => ['little\cron\event\OnCronCronQueryById'],
		'OnCronCronQueryByField' => ['little\cron\event\OnCronCronQueryByField'],
		'OnCronCronQueryByFind' => ['little\cron\event\OnCronCronQueryByFind'],
		'OnCronCronQueryByList' => ['little\cron\event\OnCronCronQueryByList'],
		'OnCronCronDeleteById' => ['little\cron\event\OnCronCronDeleteById'],
		'OnCronCronDeleteByWhere' => ['little\cron\event\OnCronCronDeleteByWhere'],
		'OnCronCronUpdateById' => ['little\cron\event\OnCronCronUpdateById'],
		'OnCronCronUpdateByWhere' => ['little\cron\event\OnCronCronUpdateByWhere'],
		'OnCronCronSave' => ['little\cron\event\OnCronCronSave'],
		'OnCronLogReadAfter' => ['little\cron\event\OnCronLogReadAfter'],
		'OnCronLogSetIncByField' => ['little\cron\event\OnCronLogSetIncByField'],
		'OnCronLogSetDecByField' => ['little\cron\event\OnCronLogSetDecByField'],
		'OnCronLogQueryById' => ['little\cron\event\OnCronLogQueryById'],
		'OnCronLogQueryByField' => ['little\cron\event\OnCronLogQueryByField'],
		'OnCronLogQueryByFind' => ['little\cron\event\OnCronLogQueryByFind'],
		'OnCronLogQueryByList' => ['little\cron\event\OnCronLogQueryByList'],
		'OnCronLogDeleteById' => ['little\cron\event\OnCronLogDeleteById'],
		'OnCronLogDeleteByWhere' => ['little\cron\event\OnCronLogDeleteByWhere'],
		'OnCronLogUpdateById' => ['little\cron\event\OnCronLogUpdateById'],
		'OnCronLogUpdateByWhere' => ['little\cron\event\OnCronLogUpdateByWhere'],
		'OnCronLogSave' => ['little\cron\event\OnCronLogSave'],
	],
	'subscribe' => [],
];