<?php

return [
	'bind' => [],
	'listen' => [
		'OnAlbumListReadAfter' => ['little\album\event\OnAlbumListReadAfter'],
		'OnAlbumListSetIncByField' => ['little\album\event\OnAlbumListSetIncByField'],
		'OnAlbumListSetDecByField' => ['little\album\event\OnAlbumListSetDecByField'],
		'OnAlbumListQueryById' => ['little\album\event\OnAlbumListQueryById'],
		'OnAlbumListQueryByField' => ['little\album\event\OnAlbumListQueryByField'],
		'OnAlbumListQueryByFind' => ['little\album\event\OnAlbumListQueryByFind'],
		'OnAlbumListQueryByList' => ['little\album\event\OnAlbumListQueryByList'],
		'OnAlbumListDeleteById' => ['little\album\event\OnAlbumListDeleteById'],
		'OnAlbumListDeleteByWhere' => ['little\album\event\OnAlbumListDeleteByWhere'],
		'OnAlbumListUpdateById' => ['little\album\event\OnAlbumListUpdateById'],
		'OnAlbumListUpdateByWhere' => ['little\album\event\OnAlbumListUpdateByWhere'],
		'OnAlbumListSave' => ['little\album\event\OnAlbumListSave'],
		'OnAlbumPicReadAfter' => ['little\album\event\OnAlbumPicReadAfter'],
		'OnAlbumPicSetIncByField' => ['little\album\event\OnAlbumPicSetIncByField'],
		'OnAlbumPicSetDecByField' => ['little\album\event\OnAlbumPicSetDecByField'],
		'OnAlbumPicQueryById' => ['little\album\event\OnAlbumPicQueryById'],
		'OnAlbumPicQueryByField' => ['little\album\event\OnAlbumPicQueryByField'],
		'OnAlbumPicQueryByFind' => ['little\album\event\OnAlbumPicQueryByFind'],
		'OnAlbumPicQueryByList' => ['little\album\event\OnAlbumPicQueryByList'],
		'OnAlbumPicDeleteById' => ['little\album\event\OnAlbumPicDeleteById'],
		'OnAlbumPicDeleteByWhere' => ['little\album\event\OnAlbumPicDeleteByWhere'],
		'OnAlbumPicUpdateById' => ['little\album\event\OnAlbumPicUpdateById'],
		'OnAlbumPicUpdateByWhere' => ['little\album\event\OnAlbumPicUpdateByWhere'],
		'OnAlbumPicSave' => ['little\album\event\OnAlbumPicSave'],
	],
	'subscribe' => [],
];