<?php

return [
	'bind' => [],
	'listen' => [
		'OnAlbumReadAfter' => ['little\album\event\OnAlbumReadAfter'],
		'OnAlbumSetIncByField' => ['little\album\event\OnAlbumSetIncByField'],
		'OnAlbumSetDecByField' => ['little\album\event\OnAlbumSetDecByField'],
		'OnAlbumQueryById' => ['little\album\event\OnAlbumQueryById'],
		'OnAlbumQueryByField' => ['little\album\event\OnAlbumQueryByField'],
		'OnAlbumQueryByFind' => ['little\album\event\OnAlbumQueryByFind'],
		'OnAlbumQueryByList' => ['little\album\event\OnAlbumQueryByList'],
		'OnAlbumDeleteById' => ['little\album\event\OnAlbumDeleteById'],
		'OnAlbumDeleteByWhere' => ['little\album\event\OnAlbumDeleteByWhere'],
		'OnAlbumUpdateById' => ['little\album\event\OnAlbumUpdateById'],
		'OnAlbumUpdateByWhere' => ['little\album\event\OnAlbumUpdateByWhere'],
		'OnAlbumSave' => ['little\album\event\OnAlbumSave'],
		'OnAlbumPicReadAfter' => ['little\album\event\OnAlbumPicReadAfter'],
		'OnAlbumPicSetIncByField' => ['little\album\event\OnAlbumPicSetIncByField'],
		'OnAlbumPicSetDecByField' => ['little\album\event\OnAlbumPicSetDecByField'],
		'OnAlbumPicQueryById' => ['little\album\event\OnAlbumPicQueryById'],
		'OnAlbumPicQueryByField' => ['little\album\event\OnAlbumPicQueryByField'],
		'OnAlbumPicQueryByFind' => ['little\album\event\OnAlbumPicQueryByFind'],
		'OnAlbumPicQueryByList' => ['little\album\event\OnAlbumPicQueryByList'],
		'OnAlbumPicDeleteById' => ['little\album\event\OnAlbumPicDeleteById'],
		'OnAlbumPicDeleteByWhere' => ['little\album\event\OnAlbumPicDeleteByWhere'],
		'OnAlbumPicUpdateById' => ['little\album\event\OnAlbumPicUpdateById'],
		'OnAlbumPicUpdateByWhere' => ['little\album\event\OnAlbumPicUpdateByWhere'],
		'OnAlbumPicSave' => ['little\album\event\OnAlbumPicSave'],
	],
	'subscribe' => [],
];