<?php

return [
	'bind' => [],
	'listen' => [
		'OnAdvReadAfter' => ['little\adv\event\OnAdvReadAfter'],
		'OnAdvSetIncByField' => ['little\adv\event\OnAdvSetIncByField'],
		'OnAdvSetDecByField' => ['little\adv\event\OnAdvSetDecByField'],
		'OnAdvQueryById' => ['little\adv\event\OnAdvQueryById'],
		'OnAdvQueryByField' => ['little\adv\event\OnAdvQueryByField'],
		'OnAdvQueryByFind' => ['little\adv\event\OnAdvQueryByFind'],
		'OnAdvQueryByList' => ['little\adv\event\OnAdvQueryByList'],
		'OnAdvDeleteById' => ['little\adv\event\OnAdvDeleteById'],
		'OnAdvDeleteByWhere' => ['little\adv\event\OnAdvDeleteByWhere'],
		'OnAdvUpdateById' => ['little\adv\event\OnAdvUpdateById'],
		'OnAdvUpdateByWhere' => ['little\adv\event\OnAdvUpdateByWhere'],
		'OnAdvSave' => ['little\adv\event\OnAdvSave'],
		'OnAdvPositionReadAfter' => ['little\adv\event\OnAdvPositionReadAfter'],
		'OnAdvPositionSetIncByField' => ['little\adv\event\OnAdvPositionSetIncByField'],
		'OnAdvPositionSetDecByField' => ['little\adv\event\OnAdvPositionSetDecByField'],
		'OnAdvPositionQueryById' => ['little\adv\event\OnAdvPositionQueryById'],
		'OnAdvPositionQueryByField' => ['little\adv\event\OnAdvPositionQueryByField'],
		'OnAdvPositionQueryByFind' => ['little\adv\event\OnAdvPositionQueryByFind'],
		'OnAdvPositionQueryByList' => ['little\adv\event\OnAdvPositionQueryByList'],
		'OnAdvPositionDeleteById' => ['little\adv\event\OnAdvPositionDeleteById'],
		'OnAdvPositionDeleteByWhere' => ['little\adv\event\OnAdvPositionDeleteByWhere'],
		'OnAdvPositionUpdateById' => ['little\adv\event\OnAdvPositionUpdateById'],
		'OnAdvPositionUpdateByWhere' => ['little\adv\event\OnAdvPositionUpdateByWhere'],
		'OnAdvPositionSave' => ['little\adv\event\OnAdvPositionSave'],
	],
	'subscribe' => [],
];