<?php

return [
	'service.shop.AccountService' => 'little\shop\service\admin\AccountService',
	'service.shop.AddressService' => 'little\shop\service\admin\AddressService',
	'service.shop.ApplyService' => 'little\shop\service\admin\ApplyService',
	'service.shop.CategoryService' => 'little\shop\service\admin\CategoryService',
	'service.shop.CertService' => 'little\shop\service\admin\CertService',
	'service.shop.DepositService' => 'little\shop\service\admin\DepositService',
	'service.shop.GroupService' => 'little\shop\service\admin\GroupService',
	'service.shop.LevelService' => 'little\shop\service\admin\LevelService',
	'service.shop.MemberService' => 'little\shop\service\admin\MemberService',
	'service.shop.OpenAccountService' => 'little\shop\service\admin\OpenAccountService',
	'service.shop.ReopenService' => 'little\shop\service\admin\ReopenService',
	'service.shop.ServiceService' => 'little\shop\service\admin\ServiceService',
	'service.shop.SettlementService' => 'little\shop\service\admin\SettlementService',
	'service.shop.SettlementPeriodService' => 'little\shop\service\admin\SettlementPeriodService',
	'service.shop.ShopService' => 'little\shop\service\admin\ShopService',
	'service.shop.WithdrawService' => 'little\shop\service\admin\WithdrawService',
	'service.shop.WithdrawPeriodService' => 'little\shop\service\admin\WithdrawPeriodService',
	'service.admin.shop.AccountService' => 'little\shop\service\admin\AccountService',
	'service.admin.shop.AddressService' => 'little\shop\service\admin\AddressService',
	'service.admin.shop.ApplyService' => 'little\shop\service\admin\ApplyService',
	'service.admin.shop.CategoryService' => 'little\shop\service\admin\CategoryService',
	'service.admin.shop.CertService' => 'little\shop\service\admin\CertService',
	'service.admin.shop.DepositService' => 'little\shop\service\admin\DepositService',
	'service.admin.shop.GroupService' => 'little\shop\service\admin\GroupService',
	'service.admin.shop.LevelService' => 'little\shop\service\admin\LevelService',
	'service.admin.shop.MemberService' => 'little\shop\service\admin\MemberService',
	'service.admin.shop.OpenAccountService' => 'little\shop\service\admin\OpenAccountService',
	'service.admin.shop.ReopenService' => 'little\shop\service\admin\ReopenService',
	'service.admin.shop.ServiceService' => 'little\shop\service\admin\ServiceService',
	'service.admin.shop.SettlementService' => 'little\shop\service\admin\SettlementService',
	'service.admin.shop.SettlementPeriodService' => 'little\shop\service\admin\SettlementPeriodService',
	'service.admin.shop.ShopService' => 'little\shop\service\admin\ShopService',
	'service.admin.shop.WithdrawService' => 'little\shop\service\admin\WithdrawService',
	'service.admin.shop.WithdrawPeriodService' => 'little\shop\service\admin\WithdrawPeriodService',
];