<?php

return [
	'bind' => [],
	'listen' => [
		'OnExchangeListReadAfter' => ['little\exchange\event\OnExchangeListReadAfter'],
		'OnExchangeListSetIncByField' => ['little\exchange\event\OnExchangeListSetIncByField'],
		'OnExchangeListSetDecByField' => ['little\exchange\event\OnExchangeListSetDecByField'],
		'OnExchangeListQueryById' => ['little\exchange\event\OnExchangeListQueryById'],
		'OnExchangeListQueryByField' => ['little\exchange\event\OnExchangeListQueryByField'],
		'OnExchangeListQueryByFind' => ['little\exchange\event\OnExchangeListQueryByFind'],
		'OnExchangeListQueryByList' => ['little\exchange\event\OnExchangeListQueryByList'],
		'OnExchangeListDeleteById' => ['little\exchange\event\OnExchangeListDeleteById'],
		'OnExchangeListDeleteByWhere' => ['little\exchange\event\OnExchangeListDeleteByWhere'],
		'OnExchangeListUpdateById' => ['little\exchange\event\OnExchangeListUpdateById'],
		'OnExchangeListUpdateByWhere' => ['little\exchange\event\OnExchangeListUpdateByWhere'],
		'OnExchangeListSave' => ['little\exchange\event\OnExchangeListSave'],
		'OnExchangeOrderReadAfter' => ['little\exchange\event\OnExchangeOrderReadAfter'],
		'OnExchangeOrderSetIncByField' => ['little\exchange\event\OnExchangeOrderSetIncByField'],
		'OnExchangeOrderSetDecByField' => ['little\exchange\event\OnExchangeOrderSetDecByField'],
		'OnExchangeOrderQueryById' => ['little\exchange\event\OnExchangeOrderQueryById'],
		'OnExchangeOrderQueryByField' => ['little\exchange\event\OnExchangeOrderQueryByField'],
		'OnExchangeOrderQueryByFind' => ['little\exchange\event\OnExchangeOrderQueryByFind'],
		'OnExchangeOrderQueryByList' => ['little\exchange\event\OnExchangeOrderQueryByList'],
		'OnExchangeOrderDeleteById' => ['little\exchange\event\OnExchangeOrderDeleteById'],
		'OnExchangeOrderDeleteByWhere' => ['little\exchange\event\OnExchangeOrderDeleteByWhere'],
		'OnExchangeOrderUpdateById' => ['little\exchange\event\OnExchangeOrderUpdateById'],
		'OnExchangeOrderUpdateByWhere' => ['little\exchange\event\OnExchangeOrderUpdateByWhere'],
		'OnExchangeOrderSave' => ['little\exchange\event\OnExchangeOrderSave'],
	],
	'subscribe' => [],
];