<?php

return [
	'bind' => [],
	'listen' => [
		'OnExchangeExchangeReadAfter' => ['little\exchange\event\OnExchangeExchangeReadAfter'],
		'OnExchangeExchangeSetIncByField' => ['little\exchange\event\OnExchangeExchangeSetIncByField'],
		'OnExchangeExchangeSetDecByField' => ['little\exchange\event\OnExchangeExchangeSetDecByField'],
		'OnExchangeExchangeQueryById' => ['little\exchange\event\OnExchangeExchangeQueryById'],
		'OnExchangeExchangeQueryByField' => ['little\exchange\event\OnExchangeExchangeQueryByField'],
		'OnExchangeExchangeQueryByFind' => ['little\exchange\event\OnExchangeExchangeQueryByFind'],
		'OnExchangeExchangeQueryByList' => ['little\exchange\event\OnExchangeExchangeQueryByList'],
		'OnExchangeExchangeDeleteById' => ['little\exchange\event\OnExchangeExchangeDeleteById'],
		'OnExchangeExchangeDeleteByWhere' => ['little\exchange\event\OnExchangeExchangeDeleteByWhere'],
		'OnExchangeExchangeUpdateById' => ['little\exchange\event\OnExchangeExchangeUpdateById'],
		'OnExchangeExchangeUpdateByWhere' => ['little\exchange\event\OnExchangeExchangeUpdateByWhere'],
		'OnExchangeExchangeSave' => ['little\exchange\event\OnExchangeExchangeSave'],
		'OnExchangeOrderReadAfter' => ['little\exchange\event\OnExchangeOrderReadAfter'],
		'OnExchangeOrderSetIncByField' => ['little\exchange\event\OnExchangeOrderSetIncByField'],
		'OnExchangeOrderSetDecByField' => ['little\exchange\event\OnExchangeOrderSetDecByField'],
		'OnExchangeOrderQueryById' => ['little\exchange\event\OnExchangeOrderQueryById'],
		'OnExchangeOrderQueryByField' => ['little\exchange\event\OnExchangeOrderQueryByField'],
		'OnExchangeOrderQueryByFind' => ['little\exchange\event\OnExchangeOrderQueryByFind'],
		'OnExchangeOrderQueryByList' => ['little\exchange\event\OnExchangeOrderQueryByList'],
		'OnExchangeOrderDeleteById' => ['little\exchange\event\OnExchangeOrderDeleteById'],
		'OnExchangeOrderDeleteByWhere' => ['little\exchange\event\OnExchangeOrderDeleteByWhere'],
		'OnExchangeOrderUpdateById' => ['little\exchange\event\OnExchangeOrderUpdateById'],
		'OnExchangeOrderUpdateByWhere' => ['little\exchange\event\OnExchangeOrderUpdateByWhere'],
		'OnExchangeOrderSave' => ['little\exchange\event\OnExchangeOrderSave'],
	],
	'subscribe' => [],
];