<?php

return [
	'bind' => [],
	'listen' => [
		'OnSystemConfigReadAfter' => ['little\system\event\OnSystemConfigReadAfter'],
		'OnSystemConfigSetIncByField' => ['little\system\event\OnSystemConfigSetIncByField'],
		'OnSystemConfigSetDecByField' => ['little\system\event\OnSystemConfigSetDecByField'],
		'OnSystemConfigQueryById' => ['little\system\event\OnSystemConfigQueryById'],
		'OnSystemConfigQueryByField' => ['little\system\event\OnSystemConfigQueryByField'],
		'OnSystemConfigQueryByFind' => ['little\system\event\OnSystemConfigQueryByFind'],
		'OnSystemConfigQueryByList' => ['little\system\event\OnSystemConfigQueryByList'],
		'OnSystemConfigDeleteById' => ['little\system\event\OnSystemConfigDeleteById'],
		'OnSystemConfigDeleteByWhere' => ['little\system\event\OnSystemConfigDeleteByWhere'],
		'OnSystemConfigUpdateById' => ['little\system\event\OnSystemConfigUpdateById'],
		'OnSystemConfigUpdateByWhere' => ['little\system\event\OnSystemConfigUpdateByWhere'],
		'OnSystemConfigSave' => ['little\system\event\OnSystemConfigSave'],
		'OnSystemDocumentReadAfter' => ['little\system\event\OnSystemDocumentReadAfter'],
		'OnSystemDocumentSetIncByField' => ['little\system\event\OnSystemDocumentSetIncByField'],
		'OnSystemDocumentSetDecByField' => ['little\system\event\OnSystemDocumentSetDecByField'],
		'OnSystemDocumentQueryById' => ['little\system\event\OnSystemDocumentQueryById'],
		'OnSystemDocumentQueryByField' => ['little\system\event\OnSystemDocumentQueryByField'],
		'OnSystemDocumentQueryByFind' => ['little\system\event\OnSystemDocumentQueryByFind'],
		'OnSystemDocumentQueryByList' => ['little\system\event\OnSystemDocumentQueryByList'],
		'OnSystemDocumentDeleteById' => ['little\system\event\OnSystemDocumentDeleteById'],
		'OnSystemDocumentDeleteByWhere' => ['little\system\event\OnSystemDocumentDeleteByWhere'],
		'OnSystemDocumentUpdateById' => ['little\system\event\OnSystemDocumentUpdateById'],
		'OnSystemDocumentUpdateByWhere' => ['little\system\event\OnSystemDocumentUpdateByWhere'],
		'OnSystemDocumentSave' => ['little\system\event\OnSystemDocumentSave'],
	],
	'subscribe' => [],
];